spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hashimova.gunay99@gmail.com
    password: jctsibzufyexwxek
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  port: 9090
